name = "vth-management"
compatibility_date = "2024-03-20"
pages_build_output_dir = ".vercel/output/static"

# هاد السطرين بيفرضوا تفعيل الـ nodejs_compat مباشرة من الكود
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "vth-db"
database_id = "23546669-ddc1-4dc5-8bfc-781239c60708"
